/**
 * The immutable canonical event log, against a real PostgreSQL.
 *
 * ### What these tests prove, and what they deliberately do not
 *
 * They prove the **schema**: uniqueness, constraints, ordering, and immutability.
 *
 * They do **not** prove ingestion. There is no `ingest()` in Stage 3.1 — no signature
 * verification, no contract parsing, no duplicate *classification*. The rows below are
 * inserted with raw SQL by the test itself, precisely because the pipeline that would
 * normally produce them does not exist yet.
 *
 * So when a test shows that a second row with the same `event_id` cannot be created, it
 * is proving that **the database enforces uniqueness** — the foundation ADR-0020 builds
 * on. It is *not* proving that a benign duplicate is counted and a conflicting one fails
 * closed. That behaviour is Stage 3.3, and nothing here should be read as claiming it.
 */

import { randomUUID } from 'node:crypto';

import { afterAll, beforeAll, describe, expect, it } from 'vitest';

import {
  closeDatabasePool,
  createDatabaseConfig,
  createDatabasePool,
  defaultMigrationsDirectory,
  runMigrations,
  withClient,
  withTransaction,
  type DatabaseClient,
  type DatabasePool,
} from '../index.js';
import {
  closeTestPool,
  createTestPool,
  requireTestDatabaseUrl,
  resetTestDatabase,
} from './database-test-utils.js';

const pool: DatabasePool = createTestPool({ applicationName: 'qf-event-log-test' });

/** Deterministic 32-byte digests. Obviously synthetic; no real digest is required here. */
const SEMANTIC_EVENT_DIGEST = Buffer.alloc(32, 0xa1);
const BODY_DIGEST = Buffer.alloc(32, 0xb2);
const SIGNATURE = Buffer.alloc(64, 0xc3);

interface EventRowInput {
  eventId?: string;
  eventType?: string;
  eventVersion?: number;
  source?: string;
  subjectType?: string;
  subjectId?: string;
  occurredAt?: string;
  emittedAt?: string;
  correlationId?: string;
  causationEventId?: string | null;
  payload?: Readonly<Record<string, unknown>>;
  semanticEventDigest?: Buffer;
  bodyDigest?: Buffer;
  signature?: Buffer;
  signatureAlgorithm?: string;
  signatureKeyId?: string;
}

/**
 * The envelope goes in columns; the payload goes in `payload`.
 *
 * **There is no `canonical_event` column, and that is the correction.** Storing the whole
 * event as a blob *as well as* in columns would be two representations of one accepted
 * fact — and two representations can disagree, with nothing to reconcile them against.
 * The persisted event is reconstructed from the columns plus `payload`.
 */
const INSERT_EVENT = `
INSERT INTO qf_jarvis.event (
  event_id, event_type, event_version, source,
  subject_type, subject_id,
  occurred_at, emitted_at,
  correlation_id, causation_event_id,
  payload, semantic_event_digest, body_digest,
  signature_algorithm, signature_key_id, signature_signed_at, signature
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17)
RETURNING sequence, accepted_at
`;

/** Insert one synthetic event row. Raw SQL, because Stage 3.1 has no ingestion API. */
async function insertEvent(
  client: DatabaseClient,
  input: EventRowInput = {},
): Promise<{ sequence: string; accepted_at: Date }> {
  const eventId = input.eventId ?? randomUUID();

  const result = await client.query<{ sequence: string; accepted_at: Date }>(INSERT_EVENT, [
    eventId,
    input.eventType ?? 'qf.recommendation.created',
    input.eventVersion ?? 1,
    input.source ?? 'quickfurno-core',
    input.subjectType ?? 'lead',
    input.subjectId ?? 'CORE-LEAD-00042',
    input.occurredAt ?? '2026-07-11T09:00:00Z',
    input.emittedAt ?? '2026-07-11T09:00:05Z',
    input.correlationId ?? randomUUID(),
    input.causationEventId === undefined ? null : input.causationEventId,
    // Payload only. It carries no eventId, no subject, no source — those are the
    // envelope's, and the envelope is in columns.
    JSON.stringify(input.payload ?? { synthetic: true }),
    input.semanticEventDigest ?? SEMANTIC_EVENT_DIGEST,
    input.bodyDigest ?? BODY_DIGEST,
    input.signatureAlgorithm ?? 'ed25519',
    input.signatureKeyId ?? 'test-qf-core-2026-07',
    '2026-07-11T09:00:06Z',
    input.signature ?? SIGNATURE,
  ]);

  const row = result.rows[0];
  if (row === undefined) {
    throw new Error('Expected the insert to return a row');
  }
  return row;
}

beforeAll(async () => {
  await resetTestDatabase(pool);
  await runMigrations(pool, defaultMigrationsDirectory());
});

afterAll(async () => {
  await closeTestPool(pool);
});

describe('inserting events', () => {
  it('accepts a well-formed synthetic event', async () => {
    const row = await withClient(pool, (client) => insertEvent(client));

    expect(BigInt(row.sequence)).toBeGreaterThan(0n);
    // accepted_at is generated by PostgreSQL, never supplied by a caller.
    expect(row.accepted_at).toBeInstanceOf(Date);
  });

  it('assigns a strictly increasing ingestion sequence', async () => {
    const sequences = await withClient(pool, async (client) => {
      const first = await insertEvent(client);
      const second = await insertEvent(client);
      const third = await insertEvent(client);
      return [first, second, third].map((row) => BigInt(row.sequence));
    });

    const [first, second, third] = sequences;

    if (first === undefined || second === undefined || third === undefined) {
      throw new Error('Expected three sequences');
    }

    expect(second).toBeGreaterThan(first);
    expect(third).toBeGreaterThan(second);
  });

  it('can be read back in ingestion order', async () => {
    const inserted = await withClient(pool, async (client) => {
      const rows = [];
      for (let index = 0; index < 3; index += 1) {
        rows.push(await insertEvent(client));
      }
      return rows.map((row) => BigInt(row.sequence));
    });

    const read = await withClient(pool, async (client) => {
      const result = await client.query<{ sequence: string }>(
        'SELECT sequence FROM qf_jarvis.event WHERE sequence >= $1 ORDER BY sequence ASC',
        [inserted[0]?.toString() ?? '0'],
      );
      return result.rows.map((row) => BigInt(row.sequence));
    });

    expect(read.slice(0, 3)).toStrictEqual(inserted);
  });

  it('preserves correlation and causation identifiers', async () => {
    const correlationId = randomUUID();
    const causeId = randomUUID();

    const { eventId } = await withClient(pool, async (client) => {
      await insertEvent(client, { eventId: causeId, correlationId });
      const id = randomUUID();
      await insertEvent(client, { eventId: id, correlationId, causationEventId: causeId });
      return { eventId: id };
    });

    const row = await withClient(pool, async (client) => {
      const result = await client.query<{
        correlation_id: string;
        causation_event_id: string | null;
      }>('SELECT correlation_id, causation_event_id FROM qf_jarvis.event WHERE event_id = $1', [
        eventId,
      ]);
      return result.rows[0];
    });

    expect(row?.correlation_id).toBe(correlationId);
    expect(row?.causation_event_id).toBe(causeId);
  });

  it('stores the payload, and round-trips it unchanged', async () => {
    const eventId = randomUUID();
    const payload = { recommendationId: 'REC-7', priority: 3, reasons: ['stale', 'high-value'] };

    await withClient(pool, (client) => insertEvent(client, { eventId, payload }));

    const stored = await withClient(pool, async (client) => {
      const result = await client.query<{ payload: Record<string, unknown> }>(
        'SELECT payload FROM qf_jarvis.event WHERE event_id = $1',
        [eventId],
      );
      return result.rows[0]?.payload;
    });

    expect(stored).toStrictEqual(payload);
  });
});

describe('one event has exactly one representation', () => {
  it('has a payload column and NO canonical_event column', async () => {
    // Structural, not behavioural, and deliberately so. The defect being prevented is a
    // SCHEMA that permits two representations of one accepted event — a `canonical_event`
    // blob that can drift out of agreement with the envelope columns beside it. You cannot
    // write a behavioural test for a contradiction that the schema makes possible but that
    // no current code happens to create; you can only refuse to provide the second place
    // to write it. So this asserts on the column list, which is the actual control.
    const columns = await withClient(pool, async (client) => {
      const result = await client.query<{ column_name: string }>(
        `SELECT column_name FROM information_schema.columns
          WHERE table_schema = 'qf_jarvis' AND table_name = 'event'`,
      );
      return result.rows.map((row) => row.column_name);
    });

    expect(columns).toContain('payload');
    expect(columns).not.toContain('canonical_event');

    // Renamed, and the old name is gone rather than aliased. The digest covers the WHOLE
    // canonical event, not the payload, and the column now says so.
    expect(columns).toContain('semantic_event_digest');
    expect(columns).not.toContain('payload_digest');
  });
});

describe('eventId uniqueness — the foundation Stage 3.3 will build idempotency on', () => {
  it('refuses a second row with the same eventId', async () => {
    const eventId = randomUUID();

    await withClient(pool, (client) => insertEvent(client, { eventId }));

    // NOTE: this proves the DATABASE enforces uniqueness. It does NOT prove the Stage 3.3
    // behaviour that distinguishes a benign duplicate from a conflicting one — there is
    // no ingestion pipeline yet to make that distinction.
    await expect(
      withClient(pool, (client) => insertEvent(client, { eventId })),
    ).rejects.toMatchObject({ constraint: 'event_event_id_unique' });
  });

  it('leaves exactly one row after a rejected duplicate', async () => {
    const eventId = randomUUID();

    await withClient(pool, (client) =>
      insertEvent(client, { eventId, subjectId: 'CORE-LEAD-FIRST' }),
    );

    await expect(
      withClient(pool, (client) => insertEvent(client, { eventId, subjectId: 'CORE-LEAD-SECOND' })),
    ).rejects.toThrow();

    const rows = await withClient(pool, async (client) => {
      const result = await client.query<{ subject_id: string }>(
        'SELECT subject_id FROM qf_jarvis.event WHERE event_id = $1',
        [eventId],
      );
      return result.rows;
    });

    expect(rows).toHaveLength(1);
    // The first acceptance stands, unmodified.
    expect(rows[0]?.subject_id).toBe('CORE-LEAD-FIRST');
  });
});

/** A constraint case: a human label, the field to corrupt, and the constraint that must fire. */
type ConstraintCase = readonly [label: string, override: EventRowInput, constraint: string];

const DIGEST_CASES: readonly ConstraintCase[] = [
  [
    'semantic event digest',
    { semanticEventDigest: Buffer.alloc(16, 1) },
    'event_semantic_event_digest_is_sha256',
  ],
  ['body digest', { bodyDigest: Buffer.alloc(31, 1) }, 'event_body_digest_is_sha256'],
];

const EMPTY_TEXT_CASES: readonly ConstraintCase[] = [
  ['subject type', { subjectType: '' }, 'event_subject_type_is_machine_token'],
  ['subject id', { subjectId: '' }, 'event_subject_id_is_opaque_core_reference'],
  ['event type', { eventType: '' }, 'event_type_is_machine_token'],
  ['signature key id', { signatureKeyId: '' }, 'event_signature_key_id_bounds'],
];

describe('constraints', () => {
  it('refuses an event that causally references itself', async () => {
    const eventId = randomUUID();

    await expect(
      withClient(pool, (client) => insertEvent(client, { eventId, causationEventId: eventId })),
    ).rejects.toMatchObject({ constraint: 'event_causation_is_not_self' });
  });

  it.each(DIGEST_CASES)(
    'refuses a %s that is not 32 bytes',
    async (_label, override, constraint) => {
      await expect(
        withClient(pool, (client) => insertEvent(client, override)),
      ).rejects.toMatchObject({
        constraint,
      });
    },
  );

  it('refuses an empty signature', async () => {
    await expect(
      withClient(pool, (client) => insertEvent(client, { signature: Buffer.alloc(0) })),
    ).rejects.toMatchObject({ constraint: 'event_signature_not_empty' });
  });

  it.each([0, -1, 1001])('refuses event version %i', async (eventVersion) => {
    await expect(
      withClient(pool, (client) => insertEvent(client, { eventVersion })),
    ).rejects.toMatchObject({ constraint: 'event_version_is_positive_and_bounded' });
  });

  it('refuses a source that is not QuickFurno Core', async () => {
    await expect(
      withClient(pool, (client) => insertEvent(client, { source: 'qf-jarvis' })),
    ).rejects.toMatchObject({ constraint: 'event_source_is_quickfurno_core' });
  });

  it('refuses an event emitted before it occurred', async () => {
    await expect(
      withClient(pool, (client) =>
        insertEvent(client, {
          occurredAt: '2026-07-11T09:00:05Z',
          emittedAt: '2026-07-11T09:00:00Z',
        }),
      ),
    ).rejects.toMatchObject({ constraint: 'event_emitted_at_not_before_occurred_at' });
  });

  it.each(EMPTY_TEXT_CASES)('refuses an empty %s', async (_label, override, constraint) => {
    await expect(withClient(pool, (client) => insertEvent(client, override))).rejects.toMatchObject(
      {
        constraint,
      },
    );
  });
});

/**
 * The constraints that mirror the STABLE Phase 2 shapes.
 *
 * They are not a second copy of Zod. Zod validates the contract; these enforce the few
 * things PostgreSQL can enforce cheaply and that will not move under us — bounds,
 * character sets, and two literals. What they buy is that a bug in some future ingestion
 * path cannot write a row the contracts would have refused.
 */

/** `MACHINE_TOKEN_PATTERN` — `^[a-z0-9]+([-.][a-z0-9]+)*$` — from the Phase 2 contracts. */
const INVALID_MACHINE_TOKENS: readonly string[] = [
  'QF.Recommendation.Created', // uppercase
  'qf_recommendation_created', // underscore is not a separator
  'qf..recommendation', // empty segment
  '.qf.recommendation', // leading separator
  'qf.recommendation.', // trailing separator
  'qf recommendation', // space
  'qf.recommendation!', // punctuation
  '', // empty
];

/** The opaque-identifier character set — `[A-Za-z0-9._:-]` — from the Phase 2 contracts. */
const INVALID_SUBJECT_IDS: readonly string[] = [
  'client@example.com', // an email address. '@' is excluded, structurally
  '+919876543210', // an E.164 phone number. '+' is excluded, structurally
  'CORE LEAD 42', // space
  'CORE/LEAD/42', // slash
  'CORE#42', // punctuation outside the set
  '', // empty
];

describe('contract-aligned constraints', () => {
  it.each(INVALID_MACHINE_TOKENS)('refuses the event type "%s"', async (eventType) => {
    await expect(
      withClient(pool, (client) => insertEvent(client, { eventType })),
    ).rejects.toMatchObject({ constraint: 'event_type_is_machine_token' });
  });

  it('refuses an event type longer than 64 characters', async () => {
    await expect(
      withClient(pool, (client) => insertEvent(client, { eventType: 'a'.repeat(65) })),
    ).rejects.toMatchObject({ constraint: 'event_type_is_machine_token' });
  });

  it.each(INVALID_MACHINE_TOKENS)('refuses the subject type "%s"', async (subjectType) => {
    await expect(
      withClient(pool, (client) => insertEvent(client, { subjectType })),
    ).rejects.toMatchObject({ constraint: 'event_subject_type_is_machine_token' });
  });

  it('refuses a subject type longer than 64 characters', async () => {
    await expect(
      withClient(pool, (client) => insertEvent(client, { subjectType: 'a'.repeat(65) })),
    ).rejects.toMatchObject({ constraint: 'event_subject_type_is_machine_token' });
  });

  it.each(INVALID_SUBJECT_IDS)('refuses the subject id "%s"', async (subjectId) => {
    await expect(
      withClient(pool, (client) => insertEvent(client, { subjectId })),
    ).rejects.toMatchObject({ constraint: 'event_subject_id_is_opaque_core_reference' });
  });

  it('refuses a subject id longer than 128 characters', async () => {
    await expect(
      withClient(pool, (client) => insertEvent(client, { subjectId: 'A'.repeat(129) })),
    ).rejects.toMatchObject({ constraint: 'event_subject_id_is_opaque_core_reference' });
  });

  it('refuses a signature algorithm that is not ed25519', async () => {
    // ADR-0020 approves exactly one algorithm, and it is asymmetric so that Jarvis holds
    // only public keys. A second accepted algorithm is a second way in.
    await expect(
      withClient(pool, (client) => insertEvent(client, { signatureAlgorithm: 'hmac-sha256' })),
    ).rejects.toMatchObject({ constraint: 'event_signature_algorithm_is_ed25519' });
  });

  it('accepts a subject type it has never seen — the taxonomy is Core’s, not ours', async () => {
    // NOT a closed enum. Core owns its entity taxonomy and Phase 3 has not integrated with
    // Core, so a constraint listing `lead`, `vendor`, `client` would be inventing a fact
    // about a system nobody here has looked at.
    const row = await withClient(pool, (client) =>
      insertEvent(client, { subjectType: 'some-future-core-entity' }),
    );

    expect(BigInt(row.sequence)).toBeGreaterThan(0n);
  });

  it.each([
    ['a hyphenated Core reference', 'CORE-LEAD-00042'],
    ['a bare digit run', '919876543210'],
    ['a UUID', '6f1b3f5e-2b7a-4f0d-9a1e-2c3d4e5f6a7b'],
    ['a colon-namespaced id', 'core:lead:42'],
    ['a dotted id', 'core.lead.42'],
  ])('accepts %s as a subject id', async (_label, subjectId) => {
    // subject_id is TEXT, never UUID. Core chooses its identifier scheme; a UUID column
    // here would be a guess about Core's database — and a bare digit run must be accepted,
    // because excluding it would be the same guess wearing a privacy costume.
    const row = await withClient(pool, (client) => insertEvent(client, { subjectId }));

    expect(BigInt(row.sequence)).toBeGreaterThan(0n);
  });
});

describe('the event log is immutable', () => {
  it('refuses UPDATE, and leaves the row unchanged', async () => {
    const eventId = randomUUID();
    await withClient(pool, (client) =>
      insertEvent(client, { eventId, subjectId: 'CORE-LEAD-ORIGINAL' }),
    );

    await expect(
      withClient(pool, (client) =>
        client.query('UPDATE qf_jarvis.event SET subject_id = $1 WHERE event_id = $2', [
          'CORE-LEAD-TAMPERED',
          eventId,
        ]),
      ),
    ).rejects.toThrow(/append-only|not permitted/i);

    const row = await withClient(pool, async (client) => {
      const result = await client.query<{ subject_id: string }>(
        'SELECT subject_id FROM qf_jarvis.event WHERE event_id = $1',
        [eventId],
      );
      return result.rows[0];
    });

    expect(row?.subject_id).toBe('CORE-LEAD-ORIGINAL');
  });

  it('refuses DELETE, and the row survives', async () => {
    const eventId = randomUUID();
    await withClient(pool, (client) => insertEvent(client, { eventId }));

    await expect(
      withClient(pool, (client) =>
        client.query('DELETE FROM qf_jarvis.event WHERE event_id = $1', [eventId]),
      ),
    ).rejects.toThrow(/append-only|not permitted/i);

    const count = await withClient(pool, async (client) => {
      const result = await client.query<{ count: string }>(
        'SELECT count(*)::text AS count FROM qf_jarvis.event WHERE event_id = $1',
        [eventId],
      );
      return Number.parseInt(result.rows[0]?.count ?? '0', 10);
    });

    expect(count).toBe(1);
  });

  it('refuses a bulk DELETE, so the whole log cannot be wiped', async () => {
    await withClient(pool, (client) => insertEvent(client));

    await expect(
      withClient(pool, (client) => client.query('DELETE FROM qf_jarvis.event')),
    ).rejects.toThrow(/append-only|not permitted/i);
  });

  it('still permits INSERT and SELECT', async () => {
    const eventId = randomUUID();
    await withClient(pool, (client) => insertEvent(client, { eventId }));

    const found = await withClient(pool, async (client) => {
      const result = await client.query('SELECT 1 FROM qf_jarvis.event WHERE event_id = $1', [
        eventId,
      ]);
      return result.rowCount;
    });

    expect(found).toBe(1);
  });
});

describe('durability', () => {
  it('data survives closing and reopening the pool', async () => {
    const eventId = randomUUID();
    await withClient(pool, (client) => insertEvent(client, { eventId }));

    const fresh = createDatabasePool(
      createDatabaseConfig({
        connectionString: requireTestDatabaseUrl(),
        applicationName: 'qf-event-log-reopen-test',
      }),
    );

    try {
      const count = await withClient(fresh, async (client) => {
        const result = await client.query<{ count: string }>(
          'SELECT count(*)::text AS count FROM qf_jarvis.event WHERE event_id = $1',
          [eventId],
        );
        return Number.parseInt(result.rows[0]?.count ?? '0', 10);
      });

      expect(count).toBe(1);
    } finally {
      await closeDatabasePool(fresh);
    }
  });
});

describe('the transaction helper', () => {
  it('commits on success', async () => {
    const eventId = randomUUID();

    await withTransaction(pool, (client) => insertEvent(client, { eventId }));

    const count = await withClient(pool, async (client) => {
      const result = await client.query<{ count: string }>(
        'SELECT count(*)::text AS count FROM qf_jarvis.event WHERE event_id = $1',
        [eventId],
      );
      return Number.parseInt(result.rows[0]?.count ?? '0', 10);
    });

    expect(count).toBe(1);
  });

  it('rolls back everything when the callback throws', async () => {
    const eventId = randomUUID();
    const failure = new Error('deliberate failure after the insert');

    await expect(
      withTransaction(pool, async (client) => {
        await insertEvent(client, { eventId });
        throw failure;
      }),
    ).rejects.toBe(failure);

    const count = await withClient(pool, async (client) => {
      const result = await client.query<{ count: string }>(
        'SELECT count(*)::text AS count FROM qf_jarvis.event WHERE event_id = $1',
        [eventId],
      );
      return Number.parseInt(result.rows[0]?.count ?? '0', 10);
    });

    // The insert happened inside the transaction and did not survive it.
    expect(count).toBe(0);
  });

  it('propagates the original error, not a rollback error', async () => {
    class DomainError extends Error {}
    const original = new DomainError('the thing that actually went wrong');

    await expect(
      withTransaction(pool, () => {
        throw original;
      }),
    ).rejects.toBe(original);
  });

  it('releases the client on success and on failure', async () => {
    const before = pool.idleCount + pool.waitingCount;

    await withTransaction(pool, (client) => client.query('SELECT 1'));
    await expect(
      withTransaction(pool, () => {
        throw new Error('boom');
      }),
    ).rejects.toThrow('boom');

    // A leaked client would leave the pool permanently short of one connection.
    expect(pool.totalCount).toBeLessThanOrEqual(5);
    expect(pool.idleCount + pool.waitingCount).toBeGreaterThanOrEqual(Math.min(before, 1));
  });

  it('withClient releases the client even when the callback throws', async () => {
    await expect(
      withClient(pool, () => {
        throw new Error('boom');
      }),
    ).rejects.toThrow('boom');

    // Still usable afterwards — a leaked client would eventually deadlock this.
    const alive = await withClient(pool, async (client) => {
      const result = await client.query<{ ok: number }>('SELECT 1 AS ok');
      return result.rows[0]?.ok;
    });

    expect(alive).toBe(1);
  });
});
