/**
 * `recordIngestionRejection` against a real PostgreSQL — the append-only, payload-free rejection
 * log (Stage 3.3.3, ADR-0031, ADR-0020 §9).
 *
 * These prove the audit row stores a bounded reason code and safe evidence and NOTHING else: no
 * payload, raw body, signature, event id, correlation id, validator message, or field path. The
 * table has no column for any of those. They also prove the runtime role's **column-level** least
 * privilege: it may append the caller columns and read back only its own generated `sequence` and
 * `recorded_at`, and can neither supply those nor read the rejected content.
 *
 * All fixtures are synthetic — obviously-synthetic digests and key ids, no real record appears.
 */
import { randomUUID } from 'node:crypto';

import { afterAll, beforeAll, describe, expect, it } from 'vitest';

import {
  closeDatabasePool,
  defaultMigrationsDirectory,
  INGESTION_REJECTION_REASON_CODES,
  recordIngestionRejection,
  withClient,
  type DatabasePool,
  type IngestionRejectionRecord,
} from '../index.js';
import { runMigrations } from '../persistence/migration-runner.js';
import {
  closeTestPool,
  createRuntimePool,
  createTestPool,
  ensureManagedRolesExist,
  ensureRuntimeRoleExists,
  MANAGED_ROLES,
  resetTestDatabase,
  RUNTIME_ROLE,
} from './database-test-utils.js';

const pool: DatabasePool = createTestPool({ applicationName: 'qf-ingestion-rejection-test' });
const RUNTIME_PASSWORD = randomUUID();
const runtimePool: DatabasePool = createRuntimePool(
  RUNTIME_PASSWORD,
  'qf-ingestion-rejection-runtime',
);

/** A well-formed synthetic rejection record. */
function makeRejection(
  overrides: Partial<IngestionRejectionRecord> = {},
): IngestionRejectionRecord {
  return {
    reasonCode: 'contract-validation-failed',
    keyId: 'test-qf-core-2026-07',
    bodyDigest: Buffer.alloc(32, 0xb2),
    issueCodes: ['required', 'invalid-type'],
    issueCount: 2,
    issuesTruncated: false,
    ...overrides,
  };
}

/** The caller-supplied columns the runtime may INSERT; sequence + recorded_at are DB-generated. */
const CALLER_COLUMNS = [
  'reason_code',
  'key_id',
  'body_digest',
  'issue_codes',
  'issue_count',
  'issues_truncated',
] as const;

beforeAll(async () => {
  await resetTestDatabase(pool);
  await ensureManagedRolesExist(pool);
  await ensureRuntimeRoleExists(pool, RUNTIME_PASSWORD);
  await runMigrations(pool, defaultMigrationsDirectory());
});

afterAll(async () => {
  await closeDatabasePool(runtimePool);
  await closeTestPool(pool);
});

describe('recordIngestionRejection — a valid rejection appends exactly one row', () => {
  it('stores the row and reports a database-generated sequence and recorded_at', async () => {
    const before = Date.now();
    const recorded = await recordIngestionRejection(pool, makeRejection());

    expect(BigInt(recorded.sequence)).toBeGreaterThan(0n);
    expect(recorded.recordedAt).toBeInstanceOf(Date);
    // recorded_at is generated by PostgreSQL, never supplied — the record has no such field.
    expect(recorded.recordedAt.getTime()).toBeGreaterThanOrEqual(before - 60_000);
  });

  it('maps every field to the correct column', async () => {
    const record = makeRejection({
      reasonCode: 'unsupported-algorithm',
      keyId: 'core-2026-a',
      bodyDigest: Buffer.alloc(32, 0x11),
      issueCodes: ['unknown-field'],
      issueCount: 4,
      issuesTruncated: true,
    });
    const recorded = await recordIngestionRejection(pool, record);

    const row = await withClient(pool, async (client) => {
      const result = await client.query(
        `SELECT reason_code, key_id, body_digest, issue_codes, issue_count, issues_truncated, recorded_at
           FROM qf_jarvis.ingestion_rejection WHERE sequence = $1`,
        [recorded.sequence],
      );
      return result.rows[0] as Record<string, unknown>;
    });

    expect(row['reason_code']).toBe('unsupported-algorithm');
    expect(row['key_id']).toBe('core-2026-a');
    expect((row['body_digest'] as Buffer).equals(Buffer.alloc(32, 0x11))).toBe(true);
    expect(row['issue_codes']).toStrictEqual(['unknown-field']);
    expect(row['issue_count']).toBe(4);
    expect(row['issues_truncated']).toBe(true);
    expect(row['recorded_at']).toBeInstanceOf(Date);
  });

  it('stores a null key_id and body_digest when omitted', async () => {
    // Built inline (not via makeRejection) so keyId and bodyDigest are genuinely ABSENT — under
    // exactOptionalPropertyTypes an optional field must be omitted, not set to undefined.
    const recorded = await recordIngestionRejection(pool, {
      reasonCode: 'signature-missing',
      issueCodes: [],
      issueCount: 0,
      issuesTruncated: false,
    });

    const row = await withClient(pool, async (client) => {
      const result = await client.query<{ key_id: string | null; body_digest: Buffer | null }>(
        'SELECT key_id, body_digest FROM qf_jarvis.ingestion_rejection WHERE sequence = $1',
        [recorded.sequence],
      );
      return result.rows[0];
    });
    expect(row?.key_id).toBeNull();
    expect(row?.body_digest).toBeNull();
  });

  it('deterministically sorts and deduplicates issue codes on the way in', async () => {
    const recorded = await recordIngestionRejection(
      pool,
      makeRejection({
        issueCodes: ['unknown-field', 'required', 'unknown-field', 'invalid-type'],
        issueCount: 4,
        issuesTruncated: true,
      }),
    );

    const stored = await withClient(pool, async (client) => {
      const result = await client.query<{ issue_codes: string[] }>(
        'SELECT issue_codes FROM qf_jarvis.ingestion_rejection WHERE sequence = $1',
        [recorded.sequence],
      );
      return result.rows[0]?.issue_codes;
    });
    expect(stored).toStrictEqual(['invalid-type', 'required', 'unknown-field']);
  });
});

describe('ingestion_rejection — closed-set and invariant constraints', () => {
  it('refuses an unknown reason code', async () => {
    await expect(
      withClient(pool, (client) =>
        client.query(
          `INSERT INTO qf_jarvis.ingestion_rejection (reason_code, issue_count) VALUES ('not-a-reason', 0)`,
        ),
      ),
    ).rejects.toMatchObject({ constraint: 'ingestion_rejection_reason_code_is_known' });
  });

  it('accepts EVERY TypeScript reason code against the applied CHECK (real insertion loop)', async () => {
    // Proves the SQL CHECK admits exactly the TypeScript vocabulary — each code inserts cleanly.
    expect(INGESTION_REJECTION_REASON_CODES.length).toBeGreaterThan(0);
    for (const reasonCode of INGESTION_REJECTION_REASON_CODES) {
      const recorded = await recordIngestionRejection(pool, {
        reasonCode,
        issueCodes: [],
        issueCount: 0,
        issuesTruncated: false,
      });
      expect(BigInt(recorded.sequence)).toBeGreaterThan(0n);
    }
  });

  it('refuses an issue code outside the safe vocabulary', async () => {
    await expect(
      withClient(pool, (client) =>
        client.query(
          `INSERT INTO qf_jarvis.ingestion_rejection (reason_code, issue_codes, issue_count)
             VALUES ('contract-validation-failed', ARRAY['not-a-code']::text[], 1)`,
        ),
      ),
    ).rejects.toMatchObject({ constraint: 'ingestion_rejection_issue_codes_are_safe' });
  });

  it('refuses duplicate issue codes', async () => {
    await expect(
      withClient(pool, (client) =>
        client.query(
          `INSERT INTO qf_jarvis.ingestion_rejection (reason_code, issue_codes, issue_count)
             VALUES ('contract-validation-failed', ARRAY['required','required']::text[], 2)`,
        ),
      ),
    ).rejects.toMatchObject({ constraint: 'ingestion_rejection_issue_codes_distinct' });
  });

  it('refuses an issue_count below the number of distinct codes', async () => {
    await expect(
      withClient(pool, (client) =>
        client.query(
          `INSERT INTO qf_jarvis.ingestion_rejection (reason_code, issue_codes, issue_count)
             VALUES ('contract-validation-failed', ARRAY['required','invalid-type']::text[], 1)`,
        ),
      ),
    ).rejects.toMatchObject({ constraint: 'ingestion_rejection_count_ge_cardinality' });
  });

  it('refuses an issue_count above the maximum', async () => {
    await expect(
      withClient(pool, (client) =>
        client.query(
          `INSERT INTO qf_jarvis.ingestion_rejection (reason_code, issue_count) VALUES ('signature-invalid', 17)`,
        ),
      ),
    ).rejects.toMatchObject({ constraint: 'ingestion_rejection_issue_count_bounds' });
  });

  it('refuses a body_digest that is not 32 bytes', async () => {
    await expect(
      withClient(pool, (client) =>
        client.query(
          `INSERT INTO qf_jarvis.ingestion_rejection (reason_code, body_digest) VALUES ('body-digest-mismatch', $1)`,
          [Buffer.alloc(16, 1)],
        ),
      ),
    ).rejects.toMatchObject({ constraint: 'ingestion_rejection_body_digest_is_sha256' });
  });
});

describe('ingestion_rejection — issue_count / issue_codes / issues_truncated semantics', () => {
  /** Insert directly (raw SQL) to exercise the migration CHECKs; return true if accepted. */
  async function inserts(sql: string): Promise<boolean> {
    return withClient(pool, async (client) => {
      await client.query(sql);
      return true;
    });
  }

  it('accepts distinct codes ["required"], issue_count 2, issues_truncated false — shared code is NOT truncation', async () => {
    // Two retained issues at different paths both carry code `required`. Nothing was truncated;
    // the code set is compressed to one, and issue_count remains 2.
    await expect(
      inserts(
        `INSERT INTO qf_jarvis.ingestion_rejection (reason_code, issue_codes, issue_count, issues_truncated)
           VALUES ('contract-validation-failed', ARRAY['required']::text[], 2, false)`,
      ),
    ).resolves.toBe(true);
  });

  it('accepts distinct codes ["required"], issue_count 1, issues_truncated false', async () => {
    await expect(
      inserts(
        `INSERT INTO qf_jarvis.ingestion_rejection (reason_code, issue_codes, issue_count, issues_truncated)
           VALUES ('contract-validation-failed', ARRAY['required']::text[], 1, false)`,
      ),
    ).resolves.toBe(true);
  });

  it('still rejects an issue_count below the number of distinct codes', async () => {
    await expect(
      withClient(pool, (client) =>
        client.query(
          `INSERT INTO qf_jarvis.ingestion_rejection (reason_code, issue_codes, issue_count)
             VALUES ('contract-validation-failed', ARRAY['required','invalid-type']::text[], 1)`,
        ),
      ),
    ).rejects.toMatchObject({ constraint: 'ingestion_rejection_count_ge_cardinality' });
  });

  it('accepts issues_truncated=true INDEPENDENTLY when the bounded source reports truncation', async () => {
    // Truncation is an independent fact: the upstream source dropped issues beyond its retained
    // list. It is accepted regardless of the issue_count-vs-cardinality relationship.
    await expect(
      inserts(
        `INSERT INTO qf_jarvis.ingestion_rejection (reason_code, issue_codes, issue_count, issues_truncated)
           VALUES ('contract-validation-failed', ARRAY['required']::text[], 2, true)`,
      ),
    ).resolves.toBe(true);
    await expect(
      inserts(
        `INSERT INTO qf_jarvis.ingestion_rejection (reason_code, issue_codes, issue_count, issues_truncated)
           VALUES ('contract-validation-failed', ARRAY['required','invalid-type']::text[], 2, true)`,
      ),
    ).resolves.toBe(true);
  });

  it('still rejects an issue_count above the maximum of 16', async () => {
    await expect(
      withClient(pool, (client) =>
        client.query(
          `INSERT INTO qf_jarvis.ingestion_rejection (reason_code, issue_count) VALUES ('signature-invalid', 17)`,
        ),
      ),
    ).rejects.toMatchObject({ constraint: 'ingestion_rejection_issue_count_bounds' });
  });

  it('the truncation-consistency constraint no longer exists', async () => {
    const exists = await withClient(pool, async (client) => {
      const result = await client.query<{ count: string }>(
        `SELECT count(*)::text AS count
           FROM pg_catalog.pg_constraint
          WHERE conname = 'ingestion_rejection_truncation_consistent'`,
      );
      return Number.parseInt(result.rows[0]?.count ?? '0', 10);
    });
    expect(exists).toBe(0);
  });
});

describe('ingestion_rejection — the table stores no UNBOUNDED sender content', () => {
  // Every column is bounded. The only sender-derived value is the optional key_id (the claimed
  // signing-key id, kept in the strict machine-token format); there is no raw body, payload,
  // signature bytes, event id, correlation id, validator message, or field path.
  it('has only bounded audit columns — no payload/body/signature/message/path column exists', async () => {
    const columns = await withClient(pool, async (client) => {
      const result = await client.query<{ column_name: string }>(
        `SELECT column_name FROM information_schema.columns
          WHERE table_schema = 'qf_jarvis' AND table_name = 'ingestion_rejection'`,
      );
      return result.rows.map((row) => row.column_name).sort();
    });

    expect(columns).toStrictEqual(
      [
        'body_digest',
        'issue_codes',
        'issue_count',
        'issues_truncated',
        'key_id',
        'reason_code',
        'recorded_at',
        'sequence',
      ].sort(),
    );
    // Explicitly: none of the forbidden content columns exists.
    for (const forbidden of [
      'payload',
      'raw_body',
      'body',
      'signature',
      'event_id',
      'correlation_id',
      'message',
      'issue_message',
      'issue_path',
      'path',
    ]) {
      expect(columns).not.toContain(forbidden);
    }
  });
});

describe('ingestion_rejection — append-only', () => {
  it('refuses UPDATE, DELETE, and a bulk DELETE', async () => {
    const recorded = await recordIngestionRejection(pool, makeRejection());

    await expect(
      withClient(pool, (client) =>
        client.query(
          `UPDATE qf_jarvis.ingestion_rejection SET reason_code = 'key-expired' WHERE sequence = $1`,
          [recorded.sequence],
        ),
      ),
    ).rejects.toThrow(/append-only|not permitted/i);

    await expect(
      withClient(pool, (client) =>
        client.query('DELETE FROM qf_jarvis.ingestion_rejection WHERE sequence = $1', [
          recorded.sequence,
        ]),
      ),
    ).rejects.toThrow(/append-only|not permitted/i);

    await expect(
      withClient(pool, (client) => client.query('DELETE FROM qf_jarvis.ingestion_rejection')),
    ).rejects.toThrow(/append-only|not permitted/i);
  });
});

describe('ingestion_rejection — the runtime role has exactly column-level least privilege', () => {
  it('can append and read back its own generated keys through the runtime connection', async () => {
    const recorded = await recordIngestionRejection(runtimePool, makeRejection());
    expect(BigInt(recorded.sequence)).toBeGreaterThan(0n);
    expect(recorded.recordedAt).toBeInstanceOf(Date);
  });

  it('holds INSERT on the caller columns and none on the generated columns', async () => {
    const priv = await withClient(pool, async (client) => {
      const insert = await Promise.all(
        [...CALLER_COLUMNS, 'sequence', 'recorded_at'].map(async (column) => {
          const result = await client.query<{ granted: boolean }>(
            `SELECT has_column_privilege($1, 'qf_jarvis.ingestion_rejection', $2, 'INSERT') AS granted`,
            [RUNTIME_ROLE, column],
          );
          return [column, result.rows[0]?.granted] as const;
        }),
      );
      return new Map(insert);
    });

    for (const column of CALLER_COLUMNS) {
      expect(priv.get(column)).toBe(true);
    }
    expect(priv.get('sequence')).toBe(false);
    expect(priv.get('recorded_at')).toBe(false);
  });

  it('holds SELECT on only sequence and recorded_at, not the content columns', async () => {
    const priv = await withClient(pool, async (client) => {
      const select = await Promise.all(
        ['sequence', 'recorded_at', ...CALLER_COLUMNS].map(async (column) => {
          const result = await client.query<{ granted: boolean }>(
            `SELECT has_column_privilege($1, 'qf_jarvis.ingestion_rejection', $2, 'SELECT') AS granted`,
            [RUNTIME_ROLE, column],
          );
          return [column, result.rows[0]?.granted] as const;
        }),
      );
      return new Map(select);
    });

    expect(priv.get('sequence')).toBe(true);
    expect(priv.get('recorded_at')).toBe(true);
    for (const column of CALLER_COLUMNS) {
      expect(priv.get(column)).toBe(false);
    }
  });

  it('cannot itself supply sequence or recorded_at', async () => {
    // Naming `sequence` in the column list is refused: the runtime has no INSERT privilege on it
    // (and it is GENERATED ALWAYS). Either way the append is rejected.
    await expect(
      withClient(runtimePool, (client) =>
        client.query(
          `INSERT INTO qf_jarvis.ingestion_rejection (reason_code, sequence) VALUES ('signature-invalid', 999)`,
        ),
      ),
    ).rejects.toThrow();

    // recorded_at is an ordinary defaulted column, so the refusal is a clean permission denial.
    await expect(
      withClient(runtimePool, (client) =>
        client.query(
          `INSERT INTO qf_jarvis.ingestion_rejection (reason_code, recorded_at) VALUES ('signature-invalid', now())`,
        ),
      ),
    ).rejects.toMatchObject({ code: '42501' });
  });

  it('cannot read the rejected content — only its own generated keys', async () => {
    await expect(
      withClient(runtimePool, (client) =>
        client.query('SELECT reason_code FROM qf_jarvis.ingestion_rejection'),
      ),
    ).rejects.toMatchObject({ code: '42501' });

    await expect(
      withClient(runtimePool, (client) =>
        client.query('SELECT * FROM qf_jarvis.ingestion_rejection'),
      ),
    ).rejects.toMatchObject({ code: '42501' });

    // But SELECTing only the two granted columns works.
    const ok = await withClient(runtimePool, async (client) => {
      const result = await client.query(
        'SELECT sequence, recorded_at FROM qf_jarvis.ingestion_rejection LIMIT 1',
      );
      return result.rowCount ?? 0;
    });
    expect(ok).toBeGreaterThanOrEqual(0);
  });

  it('needs no identity-sequence privilege to append', async () => {
    const sequenceName = await withClient(pool, async (client) => {
      const result = await client.query<{ seq: string | null }>(
        `SELECT pg_get_serial_sequence('qf_jarvis.ingestion_rejection', 'sequence') AS seq`,
      );
      const seq = result.rows[0]?.seq;
      if (seq === null || seq === undefined) {
        throw new Error('Expected an identity sequence');
      }
      const priv = await client.query<{ usage: boolean; select: boolean; update: boolean }>(
        `SELECT has_sequence_privilege($1, $2, 'USAGE')  AS usage,
                has_sequence_privilege($1, $2, 'SELECT') AS select,
                has_sequence_privilege($1, $2, 'UPDATE') AS update`,
        [RUNTIME_ROLE, seq],
      );
      return priv.rows[0];
    });
    expect(sequenceName?.usage).toBe(false);
    expect(sequenceName?.select).toBe(false);
    expect(sequenceName?.update).toBe(false);
    // And the runtime append above already proved an INSERT succeeds without any sequence grant.
  });

  it('cannot reach the migration history at all', async () => {
    await expect(
      withClient(runtimePool, (client) =>
        client.query('SELECT version FROM qf_jarvis.schema_migration'),
      ),
    ).rejects.toMatchObject({ code: '42501' });
  });
});

describe('ingestion_rejection — nothing else can reach it', () => {
  it('leaves PUBLIC, anon, authenticated and service_role with no access', async () => {
    for (const grantee of ['public', ...MANAGED_ROLES]) {
      const priv = await withClient(pool, async (client) => {
        const result = await client.query<{
          schema_usage: boolean;
          seq_select: boolean;
          reason_insert: boolean;
        }>(
          `SELECT has_schema_privilege($1, 'qf_jarvis', 'USAGE')                                          AS schema_usage,
                  has_column_privilege($1, 'qf_jarvis.ingestion_rejection', 'sequence', 'SELECT')         AS seq_select,
                  has_column_privilege($1, 'qf_jarvis.ingestion_rejection', 'reason_code', 'INSERT')      AS reason_insert`,
          [grantee],
        );
        return result.rows[0];
      });
      expect(priv?.schema_usage).toBe(false);
      expect(priv?.seq_select).toBe(false);
      expect(priv?.reason_insert).toBe(false);
    }
  });
});
