/**
 * The closed, repository-owned runner error vocabulary (Stage 3.4.4, ADR-0037).
 *
 * These are the ONLY errors the projection runner throws. Each carries a stable `code` from a closed
 * table and a fixed, repository-owned message — never a raw PostgreSQL message, SQLSTATE, SQL, stack,
 * cause, caller/handler-thrown value, or any enumerable caller field. A caught handler/driver value is
 * ALWAYS discarded (never wrapped as `cause`); a fresh error with its OWN stack is thrown instead. The
 * constructor accepts only a code and normalises it at runtime, so an `as`-cast secret cannot survive
 * in `.code` any more than in `.message`.
 *
 * These are RUNNER-thrown error codes; they are distinct from the four stored `safe_error_code` values
 * (which remain the closed set in `projection-safe-error.ts`). Nothing here is exported from the
 * package root.
 */

/** The closed set of runner failure codes, each mapped to its FIXED message. */
const PROJECTION_RUNNER_ERROR_MESSAGES = {
  'projection-runner-unavailable': 'The projection runner could not obtain a database client.',
  'projection-unknown-definition':
    'No projection definition matches the requested name and version.',
  'projection-attempt-checkpoint-divergent':
    'The stored checkpoint and attempt records for the pending projection position are inconsistent.',
  'projection-infrastructure-failed':
    'A database or infrastructure failure aborted the projection run; no attempt was recorded.',
  'projection-commit-outcome-unknown':
    'The projection transaction commit outcome is unknown; the run must be re-invoked to observe the durable state.',
} as const;

/** The closed set of runner failure codes. */
export const PROJECTION_RUNNER_ERROR_CODES = Object.freeze(
  Object.keys(PROJECTION_RUNNER_ERROR_MESSAGES) as ProjectionRunnerErrorCode[],
);

/** One runner failure code. */
export type ProjectionRunnerErrorCode = keyof typeof PROJECTION_RUNNER_ERROR_MESSAGES;

/** The generic fallback applied when a supplied code is not one of the known codes. */
const RUNNER_FALLBACK_CODE: ProjectionRunnerErrorCode = 'projection-infrastructure-failed';

/** Normalise an arbitrary runtime value into a known code, or the safe fallback (hasOwnProperty gate). */
function normalizeRunnerCode(code: unknown): ProjectionRunnerErrorCode {
  return typeof code === 'string' &&
    Object.prototype.hasOwnProperty.call(PROJECTION_RUNNER_ERROR_MESSAGES, code)
    ? (code as ProjectionRunnerErrorCode)
    : RUNNER_FALLBACK_CODE;
}

/**
 * A projection run failed. The constructor takes ONLY a code (runtime-normalised); the message is the
 * fixed table entry. It retains no `cause` and no caller/driver text; its stack is freshly generated by
 * `Error` and never reuses a caught object's stack.
 */
export class ProjectionRunnerError extends Error {
  public readonly code: ProjectionRunnerErrorCode;

  public constructor(code: ProjectionRunnerErrorCode) {
    const safeCode = normalizeRunnerCode(code);
    super(PROJECTION_RUNNER_ERROR_MESSAGES[safeCode]);
    this.name = 'ProjectionRunnerError';
    this.code = safeCode;
  }
}
