/**
 * The closed, repository-owned error vocabulary for the projection-failure OPERATIONS boundary
 * (QFJ-P03.07E, ADR-0040).
 *
 * These are the only errors the inspection/acknowledge/quarantine operations throw. Each carries a
 * stable `code` from a closed table and a fixed, repository-owned message — never a raw PostgreSQL
 * message, SQLSTATE, SQL, stack, caller/operator input, event payload, or secret. A caught driver value
 * is ALWAYS discarded (never wrapped as `cause`); a fresh error with its own stack is thrown. The
 * constructor normalises the code at runtime, so an `as`-cast value cannot survive in `.code`.
 *
 * Nothing here is exported from the package root; the barrel's 39-symbol runtime surface is unchanged.
 */

/** The closed set of operation error codes, each mapped to its FIXED, operator-safe message. */
const PROJECTION_FAILURE_OPERATION_ERROR_MESSAGES = {
  'failure-not-found': 'No projection failure matches the requested identity.',
  'authorization-denied':
    'The operator is not authorized to perform this projection-failure operation.',
  'stale-generation':
    'The projection failure changed since it was read; the expected generation is stale.',
  'invalid-transition': 'The projection failure is not in a status that permits this operation.',
  'already-acknowledged': 'The projection failure has already been acknowledged.',
  'already-quarantined': 'The projection failure has already been quarantined.',
  'divergence-detected':
    'A persistence/checkpoint divergence was detected; the mutation is refused until it is reconciled.',
  'repository-unavailable': 'The projection-failure repository is unavailable.',
  'commit-outcome-unknown':
    'The operation commit outcome is unknown; re-invoke with the same idempotency key to reconcile.',
  'invalid-cursor': 'The inspection cursor is malformed.',
  'invalid-page-size': 'The requested page size is out of the permitted range.',
  'invalid-actor': 'The operator actor identity or type is invalid.',
  'invalid-reason': 'The supplied reason is invalid or exceeds its bound.',
  'invalid-correlation-id': 'The supplied correlation id is not a valid identifier.',
  'invalid-filter': 'An inspection filter value is not in the permitted closed vocabulary.',
} as const;

/** The closed set of operation error codes. */
export const PROJECTION_FAILURE_OPERATION_ERROR_CODES = Object.freeze(
  Object.keys(PROJECTION_FAILURE_OPERATION_ERROR_MESSAGES) as ProjectionFailureOperationErrorCode[],
);

/** One operation error code. */
export type ProjectionFailureOperationErrorCode =
  keyof typeof PROJECTION_FAILURE_OPERATION_ERROR_MESSAGES;

/** The safe fallback applied when a supplied code is not one of the known codes. */
const FALLBACK_CODE: ProjectionFailureOperationErrorCode = 'repository-unavailable';

/** Normalise an arbitrary runtime value into a known code, or the safe fallback (hasOwnProperty gate). */
function normalizeCode(code: unknown): ProjectionFailureOperationErrorCode {
  return typeof code === 'string' &&
    Object.prototype.hasOwnProperty.call(PROJECTION_FAILURE_OPERATION_ERROR_MESSAGES, code)
    ? (code as ProjectionFailureOperationErrorCode)
    : FALLBACK_CODE;
}

/**
 * A projection-failure operation failed. The constructor takes ONLY a code (runtime-normalised); the
 * message is the fixed table entry. It retains no `cause` and no caller/driver text; its stack is
 * freshly generated by `Error`.
 */
export class ProjectionFailureOperationError extends Error {
  public readonly code: ProjectionFailureOperationErrorCode;

  public constructor(code: ProjectionFailureOperationErrorCode) {
    const safeCode = normalizeCode(code);
    super(PROJECTION_FAILURE_OPERATION_ERROR_MESSAGES[safeCode]);
    this.name = 'ProjectionFailureOperationError';
    this.code = safeCode;
  }
}

/** Recognise an authentic {@link ProjectionFailureOperationError} without letting a hostile value throw. */
export function isProjectionFailureOperationError(
  value: unknown,
): value is ProjectionFailureOperationError {
  try {
    return value instanceof ProjectionFailureOperationError;
  } catch {
    return false;
  }
}
