/**
 * The closed, repository-owned error vocabulary for the authorized-replay boundary (QFJ-P03.07F,
 * ADR-0040).
 *
 * These are the only errors the replay authorize/execute/takeover/reconcile operations throw. Each
 * carries a stable `code` from a closed table and a fixed, repository-owned message — never a raw
 * PostgreSQL message, SQLSTATE, SQL, stack, caller/operator input, event payload, read-model row, or
 * secret. A caught driver/handler value is ALWAYS discarded (never wrapped as `cause`); a fresh error
 * with its own stack is thrown. The constructor normalises the code at runtime.
 *
 * Nothing here is exported from the package root; the barrel's 39-symbol runtime surface is unchanged.
 */

/** The closed set of replay error codes, each mapped to its FIXED, operator-safe message. */
const PROJECTION_REPLAY_ERROR_MESSAGES = {
  'authorization-denied': 'The actor is not authorized to perform this replay operation.',
  'failure-not-found': 'No projection failure matches the requested identity.',
  'invalid-source-status':
    'The projection failure is not in a status that permits this replay operation.',
  'stale-generation':
    'The projection failure changed since it was read; the expected generation is stale.',
  'divergence-detected':
    'A persistence/checkpoint divergence was detected; the replay operation is refused until it is reconciled.',
  'authorization-already-active': 'An active replay authorization already exists for this failure.',
  'authorization-not-found': 'No replay authorization matches the requested identity.',
  'authorization-not-active':
    'The replay authorization is not active (consumed, expired, or revoked).',
  'authorization-mismatch':
    'The replay authorization does not belong to this failure or its generation does not match.',
  'lease-held': 'A live replay attempt with an unexpired lease is held by another owner.',
  'lease-not-expired': 'The current replay lease has not expired; takeover is not permitted yet.',
  'attempt-not-found': 'No replay attempt matches the requested identity.',
  'attempt-not-live': 'The replay attempt is not live (already terminal).',
  'event-not-found': 'No event maps to the blocked projection position.',
  'event-identity-mismatch':
    'The event at the blocked position does not match the failure identity.',
  'unsupported-event-type': 'The blocked event type is not accepted by the registered projection.',
  'unknown-definition': 'No projection definition matches the failure name and version.',
  'replay-handler-failed': 'The projection handler deterministically refused the replayed event.',
  'infrastructure-failed':
    'A transient infrastructure failure aborted the replay; nothing was committed.',
  'repository-invariant':
    'A repository invariant was violated during replay; the operation failed closed.',
  cancelled: 'The replay was cancelled or the process is shutting down.',
  'unknown-failure': 'An unclassified failure aborted the replay; the operation failed closed.',
  'commit-outcome-unknown':
    'The replay commit outcome is unknown; reconcile with the same identity before any retry.',
  'invalid-actor': 'The actor identity or type is invalid.',
  'invalid-correlation-id': 'The supplied correlation id is not a valid identifier.',
  'invalid-reason': 'The supplied reason is invalid or exceeds its bound.',
  'invalid-identifier': 'A supplied failure/authorization/attempt identifier is invalid.',
  'invalid-expiry':
    'The authorization expiry is not a valid future instant within the permitted bound.',
  'invalid-lease-duration': 'The lease duration is not within the permitted bound.',
} as const;

/** The closed set of replay error codes. */
export const PROJECTION_REPLAY_ERROR_CODES = Object.freeze(
  Object.keys(PROJECTION_REPLAY_ERROR_MESSAGES) as ProjectionReplayErrorCode[],
);

/** One replay error code. */
export type ProjectionReplayErrorCode = keyof typeof PROJECTION_REPLAY_ERROR_MESSAGES;

/** The safe fallback applied when a supplied code is not one of the known codes. */
const FALLBACK_CODE: ProjectionReplayErrorCode = 'unknown-failure';

/** Normalise an arbitrary runtime value into a known code, or the safe fallback (hasOwnProperty gate). */
function normalizeCode(code: unknown): ProjectionReplayErrorCode {
  return typeof code === 'string' &&
    Object.prototype.hasOwnProperty.call(PROJECTION_REPLAY_ERROR_MESSAGES, code)
    ? (code as ProjectionReplayErrorCode)
    : FALLBACK_CODE;
}

/**
 * An authorized-replay operation failed. The constructor takes ONLY a code (runtime-normalised); the
 * message is the fixed table entry. It retains no `cause` and no caller/driver text; its stack is freshly
 * generated by `Error`.
 */
export class ProjectionReplayError extends Error {
  public readonly code: ProjectionReplayErrorCode;

  public constructor(code: ProjectionReplayErrorCode) {
    const safeCode = normalizeCode(code);
    super(PROJECTION_REPLAY_ERROR_MESSAGES[safeCode]);
    this.name = 'ProjectionReplayError';
    this.code = safeCode;
  }
}

/** Recognise an authentic {@link ProjectionReplayError} without letting a hostile value throw. */
export function isProjectionReplayError(value: unknown): value is ProjectionReplayError {
  try {
    return value instanceof ProjectionReplayError;
  } catch {
    return false;
  }
}
