import { createAosBehaviourPolicy, type AosBehaviourPolicy } from './behavior.js';
import { validRef } from './validation.js';

export interface AosBehaviourRegistry {
  readonly registryRef: string;
  readonly policies: readonly AosBehaviourPolicy[];
}

export function createAosBehaviourRegistry(input: AosBehaviourRegistry): AosBehaviourRegistry {
  if (!validRef(input.registryRef) || input.policies.length > 1_000) {
    throw new TypeError('aos-behaviour-registry-invalid');
  }
  const keys = new Set<string>();
  for (const policy of input.policies) {
    const key = policy.policyId + '@' + String(policy.version);
    if (keys.has(key)) throw new TypeError('aos-behaviour-registry-duplicate');
    keys.add(key);
  }
  return Object.freeze({
    registryRef: input.registryRef,
    policies: Object.freeze([...input.policies]),
  });
}

const GLOBAL_SCOPE = Object.freeze({
  cityRefs: Object.freeze([]),
  localityRefs: Object.freeze([]),
  categoryRefs: Object.freeze([]),
});

const DEFAULT_COMMUNICATION = Object.freeze({
  cooldownMinutes: 1_440,
  maxMessagesPer30Days: 4,
  quietHoursLocal: Object.freeze({ startHour: 21, endHour: 9 }),
  directPhoneAllowed: false as const,
  maskedOpportunityOnly: true,
});

export const AOS_BEHAVIOUR_REGISTRY_V1 = createAosBehaviourRegistry({
  registryRef: 'qfj.aos.behaviour-registry.v1',
  policies: [
    createAosBehaviourPolicy({
      policyId: 'lead.vendor-first-contact-recovery',
      version: 1,
      lifecycle: 'SUGGESTING',
      title: 'Vendor first-contact recovery',
      trigger: 'VENDOR_FIRST_CONTACT_MISSING',
      priority: 'P1',
      scope: GLOBAL_SCOPE,
      conditions: [{ field: 'elapsedMinutes', operator: 'GTE', value: 20 }],
      action: 'RECOMMEND_ANISHA_VENDOR_FOLLOW_UP',
      ownerApprovalRequired: false,
      coreDecisionRequired: true,
      maximumVendorExposureWithoutOwnerApproval: 3,
      communication: {
        ...DEFAULT_COMMUNICATION,
        cooldownMinutes: 10,
        maxMessagesPer30Days: 8,
      },
    }),
    createAosBehaviourPolicy({
      policyId: 'lead.replacement-vendor',
      version: 1,
      lifecycle: 'SUGGESTING',
      title: 'Replacement vendor after failed contact',
      trigger: 'LEAD_FIRST_CONTACT_GAP',
      priority: 'P1',
      scope: GLOBAL_SCOPE,
      conditions: [
        { field: 'elapsedMinutes', operator: 'GTE', value: 30 },
        { field: 'successfulVendorContacts', operator: 'LT', value: 3 },
      ],
      action: 'RECOMMEND_REPLACEMENT_VENDOR',
      ownerApprovalRequired: true,
      coreDecisionRequired: true,
      maximumVendorExposureWithoutOwnerApproval: 3,
      communication: { ...DEFAULT_COMMUNICATION, cooldownMinutes: 30 },
    }),
    createAosBehaviourPolicy({
      policyId: 'client.follow-up-due',
      version: 1,
      lifecycle: 'SUGGESTING',
      title: 'Client follow-up when Core says it is due',
      trigger: 'CLIENT_FOLLOW_UP_DUE',
      priority: 'P2',
      scope: GLOBAL_SCOPE,
      conditions: [],
      action: 'RECOMMEND_RIYA_CLIENT_FOLLOW_UP',
      ownerApprovalRequired: false,
      coreDecisionRequired: false,
      maximumVendorExposureWithoutOwnerApproval: 3,
      communication: {
        ...DEFAULT_COMMUNICATION,
        cooldownMinutes: 1_440,
        maxMessagesPer30Days: 3,
        maskedOpportunityOnly: false,
      },
    }),
    createAosBehaviourPolicy({
      policyId: 'client.post-handoff-satisfaction',
      version: 1,
      lifecycle: 'SUGGESTING',
      title: 'Post-handoff client satisfaction check',
      trigger: 'LEAD_HANDOFF_COMPLETE',
      priority: 'P2',
      scope: GLOBAL_SCOPE,
      conditions: [
        { field: 'successfulVendorContacts', operator: 'GTE', value: 3 },
        { field: 'daysSinceHandoff', operator: 'GTE', value: 2 },
      ],
      action: 'RECOMMEND_RIYA_SATISFACTION_CHECK',
      ownerApprovalRequired: false,
      coreDecisionRequired: false,
      maximumVendorExposureWithoutOwnerApproval: 3,
      communication: {
        ...DEFAULT_COMMUNICATION,
        cooldownMinutes: 2_880,
        maxMessagesPer30Days: 2,
        maskedOpportunityOnly: false,
      },
    }),
    createAosBehaviourPolicy({
      policyId: 'client.dissatisfaction-recovery',
      version: 1,
      lifecycle: 'SUGGESTING',
      title: 'Client dissatisfaction recovery',
      trigger: 'CLIENT_SATISFACTION_NEGATIVE',
      priority: 'P1',
      scope: GLOBAL_SCOPE,
      conditions: [],
      action: 'RECOMMEND_RIYA_CLIENT_FOLLOW_UP',
      ownerApprovalRequired: true,
      coreDecisionRequired: false,
      maximumVendorExposureWithoutOwnerApproval: 3,
      communication: {
        ...DEFAULT_COMMUNICATION,
        cooldownMinutes: 1_440,
        maxMessagesPer30Days: 2,
        maskedOpportunityOnly: false,
      },
    }),
    createAosBehaviourPolicy({
      policyId: 'client.related-service-expansion',
      version: 1,
      lifecycle: 'SUGGESTING',
      title: 'Relevant client service expansion',
      trigger: 'CLIENT_RELATED_SERVICE_ELIGIBLE',
      priority: 'P2',
      scope: GLOBAL_SCOPE,
      conditions: [
        { field: 'clientSatisfactionScore', operator: 'GTE', value: 0.8 },
        { field: 'relatedServiceScore', operator: 'GTE', value: 0.75 },
      ],
      action: 'RECOMMEND_RIYA_RELATED_SERVICE',
      ownerApprovalRequired: true,
      coreDecisionRequired: false,
      maximumVendorExposureWithoutOwnerApproval: 3,
      communication: {
        ...DEFAULT_COMMUNICATION,
        cooldownMinutes: 10_080,
        maxMessagesPer30Days: 2,
        maskedOpportunityOnly: false,
      },
    }),
    createAosBehaviourPolicy({
      policyId: 'vendor.low-balance',
      version: 1,
      lifecycle: 'SUGGESTING',
      title: 'Vendor low-balance alert',
      trigger: 'VENDOR_LOW_BALANCE',
      priority: 'P2',
      scope: GLOBAL_SCOPE,
      conditions: [],
      action: 'RECOMMEND_ANISHA_LOW_BALANCE_ALERT',
      ownerApprovalRequired: false,
      coreDecisionRequired: false,
      maximumVendorExposureWithoutOwnerApproval: 3,
      communication: {
        ...DEFAULT_COMMUNICATION,
        cooldownMinutes: 10_080,
        maxMessagesPer30Days: 2,
        maskedOpportunityOnly: false,
      },
    }),
    createAosBehaviourPolicy({
      policyId: 'vendor.credit-depletion',
      version: 1,
      lifecycle: 'SUGGESTING',
      title: 'Predicted vendor credit depletion',
      trigger: 'VENDOR_CREDIT_DEPLETION_PREDICTED',
      priority: 'P2',
      scope: GLOBAL_SCOPE,
      conditions: [],
      action: 'RECOMMEND_ANISHA_RECHARGE_NUDGE',
      ownerApprovalRequired: false,
      coreDecisionRequired: false,
      maximumVendorExposureWithoutOwnerApproval: 3,
      communication: {
        ...DEFAULT_COMMUNICATION,
        cooldownMinutes: 10_080,
        maxMessagesPer30Days: 2,
        maskedOpportunityOnly: false,
      },
    }),
    createAosBehaviourPolicy({
      policyId: 'vendor.recharge-opportunity',
      version: 1,
      lifecycle: 'SUGGESTING',
      title: 'Core-derived vendor recharge opportunity',
      trigger: 'VENDOR_RECHARGE_OPPORTUNITY',
      priority: 'P2',
      scope: GLOBAL_SCOPE,
      conditions: [],
      action: 'RECOMMEND_ANISHA_RECHARGE_NUDGE',
      ownerApprovalRequired: false,
      coreDecisionRequired: false,
      maximumVendorExposureWithoutOwnerApproval: 3,
      communication: {
        ...DEFAULT_COMMUNICATION,
        cooldownMinutes: 10_080,
        maxMessagesPer30Days: 2,
        maskedOpportunityOnly: false,
      },
    }),
    createAosBehaviourPolicy({
      policyId: 'vendor.package-readiness-low',
      version: 1,
      lifecycle: 'SUGGESTING',
      title: 'Low vendor package-readiness band',
      trigger: 'VENDOR_PACKAGE_READINESS_LOW',
      priority: 'P2',
      scope: GLOBAL_SCOPE,
      conditions: [],
      action: 'RECOMMEND_ANISHA_RECHARGE_NUDGE',
      ownerApprovalRequired: false,
      coreDecisionRequired: false,
      maximumVendorExposureWithoutOwnerApproval: 3,
      communication: {
        ...DEFAULT_COMMUNICATION,
        cooldownMinutes: 10_080,
        maxMessagesPer30Days: 2,
        maskedOpportunityOnly: false,
      },
    }),
    createAosBehaviourPolicy({
      policyId: 'vendor.complaint-success-recovery',
      version: 1,
      lifecycle: 'SUGGESTING',
      title: 'Vendor complaint success recovery',
      trigger: 'VENDOR_COMPLAINT_RECORDED',
      priority: 'P1',
      scope: GLOBAL_SCOPE,
      conditions: [],
      action: 'RECOMMEND_ANISHA_VENDOR_SUCCESS_CHECK',
      ownerApprovalRequired: true,
      coreDecisionRequired: false,
      maximumVendorExposureWithoutOwnerApproval: 3,
      communication: {
        ...DEFAULT_COMMUNICATION,
        cooldownMinutes: 1_440,
        maxMessagesPer30Days: 2,
        maskedOpportunityOnly: false,
      },
    }),
    createAosBehaviourPolicy({
      policyId: 'vendor.retention-risk',
      version: 1,
      lifecycle: 'SUGGESTING',
      title: 'Vendor retention-risk success check',
      trigger: 'VENDOR_RETENTION_RISK',
      priority: 'P2',
      scope: GLOBAL_SCOPE,
      conditions: [],
      action: 'RECOMMEND_ANISHA_VENDOR_SUCCESS_CHECK',
      ownerApprovalRequired: true,
      coreDecisionRequired: false,
      maximumVendorExposureWithoutOwnerApproval: 3,
      communication: {
        ...DEFAULT_COMMUNICATION,
        cooldownMinutes: 10_080,
        maxMessagesPer30Days: 2,
        maskedOpportunityOnly: false,
      },
    }),
    createAosBehaviourPolicy({
      policyId: 'vendor.winback-candidate',
      version: 1,
      lifecycle: 'SUGGESTING',
      title: 'Vendor win-back candidate',
      trigger: 'VENDOR_WINBACK_CANDIDATE',
      priority: 'P2',
      scope: GLOBAL_SCOPE,
      conditions: [],
      action: 'RECOMMEND_ANISHA_VENDOR_REACTIVATION',
      ownerApprovalRequired: true,
      coreDecisionRequired: false,
      maximumVendorExposureWithoutOwnerApproval: 3,
      communication: {
        ...DEFAULT_COMMUNICATION,
        cooldownMinutes: 43_200,
        maxMessagesPer30Days: 1,
        maskedOpportunityOnly: true,
      },
    }),
    createAosBehaviourPolicy({
      policyId: 'vendor.inactive-local-demand',
      version: 1,
      lifecycle: 'SUGGESTING',
      title: 'Inactive vendor reactivation from local demand',
      trigger: 'MATCHING_DEMAND_DETECTED',
      priority: 'P2',
      scope: GLOBAL_SCOPE,
      conditions: [
        { field: 'vendorInactiveDays', operator: 'GTE', value: 30 },
        { field: 'matchingDemandCount', operator: 'GTE', value: 1 },
      ],
      action: 'RECOMMEND_ANISHA_VENDOR_REACTIVATION',
      ownerApprovalRequired: true,
      coreDecisionRequired: false,
      maximumVendorExposureWithoutOwnerApproval: 3,
      communication: {
        ...DEFAULT_COMMUNICATION,
        cooldownMinutes: 20_160,
        maxMessagesPer30Days: 2,
        maskedOpportunityOnly: true,
      },
    }),
    createAosBehaviourPolicy({
      policyId: 'marketplace.vendor-response-degraded',
      version: 1,
      lifecycle: 'SUGGESTING',
      title: 'Marketplace vendor-response degradation',
      trigger: 'VENDOR_RESPONSE_DEGRADED',
      priority: 'P2',
      scope: GLOBAL_SCOPE,
      conditions: [],
      action: 'RECOMMEND_OWNER_REVIEW',
      ownerApprovalRequired: true,
      coreDecisionRequired: false,
      maximumVendorExposureWithoutOwnerApproval: 3,
      communication: {
        ...DEFAULT_COMMUNICATION,
        cooldownMinutes: 1_440,
        maxMessagesPer30Days: 1,
        maskedOpportunityOnly: true,
      },
    }),
    createAosBehaviourPolicy({
      policyId: 'marketplace.supply-shortage',
      version: 1,
      lifecycle: 'SUGGESTING',
      title: 'Category/locality supply shortage',
      trigger: 'SUPPLY_SHORTAGE',
      priority: 'P1',
      scope: GLOBAL_SCOPE,
      conditions: [{ field: 'matchingDemandCount', operator: 'GTE', value: 5 }],
      action: 'RECOMMEND_AAROHI_SUPPLY_ACQUISITION',
      ownerApprovalRequired: true,
      coreDecisionRequired: false,
      maximumVendorExposureWithoutOwnerApproval: 3,
      communication: {
        ...DEFAULT_COMMUNICATION,
        cooldownMinutes: 43_200,
        maxMessagesPer30Days: 1,
        maskedOpportunityOnly: true,
      },
    }),
    createAosBehaviourPolicy({
      policyId: 'marketplace.capacity-under-supplied',
      version: 1,
      lifecycle: 'SUGGESTING',
      title: 'Acquire vendors for an under-supplied market cell',
      trigger: 'MARKET_UNDER_SUPPLIED',
      priority: 'P1',
      scope: GLOBAL_SCOPE,
      conditions: [],
      action: 'RECOMMEND_AAROHI_SUPPLY_ACQUISITION',
      ownerApprovalRequired: true,
      coreDecisionRequired: false,
      maximumVendorExposureWithoutOwnerApproval: 3,
      communication: { ...DEFAULT_COMMUNICATION, cooldownMinutes: 43_200, maxMessagesPer30Days: 1 },
    }),
    createAosBehaviourPolicy({
      policyId: 'marketplace.capacity-over-supplied',
      version: 1,
      lifecycle: 'SUGGESTING',
      title: 'Review package activation in an over-supplied market cell',
      trigger: 'MARKET_OVER_SUPPLIED',
      priority: 'P2',
      scope: GLOBAL_SCOPE,
      conditions: [],
      action: 'RECOMMEND_PACKAGE_CAPACITY_HOLD',
      ownerApprovalRequired: true,
      coreDecisionRequired: true,
      maximumVendorExposureWithoutOwnerApproval: 3,
      communication: { ...DEFAULT_COMMUNICATION, cooldownMinutes: 43_200, maxMessagesPer30Days: 1 },
    }),
    createAosBehaviourPolicy({
      policyId: 'marketplace.capacity-demand-starved',
      version: 1,
      lifecycle: 'SUGGESTING',
      title: 'Increase client demand in a demand-starved market cell',
      trigger: 'MARKET_DEMAND_STARVED',
      priority: 'P2',
      scope: GLOBAL_SCOPE,
      conditions: [],
      action: 'RECOMMEND_CLIENT_DEMAND_GROWTH',
      ownerApprovalRequired: true,
      coreDecisionRequired: false,
      maximumVendorExposureWithoutOwnerApproval: 3,
      communication: { ...DEFAULT_COMMUNICATION, cooldownMinutes: 43_200, maxMessagesPer30Days: 1 },
    }),
    createAosBehaviourPolicy({
      policyId: 'marketplace.capacity-low-quality-supply',
      version: 1,
      lifecycle: 'SUGGESTING',
      title: 'Improve vendor quality in a weak-effective-supply market cell',
      trigger: 'MARKET_LOW_QUALITY_SUPPLY',
      priority: 'P1',
      scope: GLOBAL_SCOPE,
      conditions: [],
      action: 'RECOMMEND_VENDOR_QUALITY_RECOVERY',
      ownerApprovalRequired: true,
      coreDecisionRequired: false,
      maximumVendorExposureWithoutOwnerApproval: 3,
      communication: { ...DEFAULT_COMMUNICATION, cooldownMinutes: 10_080, maxMessagesPer30Days: 1 },
    }),
  ],
});
