import type {
  AgentFlowEdgeDefinition,
  AgentFlowGroupDefinition,
  AgentFlowNodeDefinition,
} from './contracts.js';
import { createAgentFlowDefinition } from './validate.js';

const groups: readonly AgentFlowGroupDefinition[] = [
  {
    groupId: 'riya.inbound',
    label: 'Inbound & durable claim',
    actor: 'SHARED',
    description: 'Durable inbound admission before any agent/model work.',
    order: 10,
  },
  {
    groupId: 'riya.context',
    label: 'Core context & memory',
    actor: 'RIYA',
    description: 'Authoritative and bounded context material consumed by Riya.',
    order: 20,
  },
  {
    groupId: 'riya.pre-agent-actions',
    label: 'Pre-agent governed actions',
    actor: 'RIYA',
    description: 'Deterministic evidence-bound actions performed before the model when eligible.',
    order: 30,
  },
  {
    groupId: 'riya.intelligence',
    label: 'Client intelligence & Riya',
    actor: 'RIYA',
    description: 'Advisory reasoning, next-best-action and specialist response generation.',
    order: 40,
  },
  {
    groupId: 'riya.response',
    label: 'Governed response',
    actor: 'SHARED',
    description: 'Core-bound reply request and durable turn finalization.',
    order: 50,
  },
] as const;

const nodes: readonly AgentFlowNodeDefinition[] = [
  {
    nodeId: 'riya.trigger.whatsapp-inbound',
    nodeVersion: 1,
    label: 'WhatsApp inbound',
    actor: 'SHARED',
    kind: 'TRIGGER',
    executionRole: 'STEP',
    stage: 'TRIGGER',
    authority: 'ORCHESTRATION_CONTROL',
    effect: 'NONE',
    status: 'IMPLEMENTED',
    implementationRef: 'apps.quickfurno-gateway',
    description: 'Validated inbound message enters the durable turn path.',
    codeLocked: true,
    canvasEditable: [],
    groupId: 'riya.inbound',
    tags: ['whatsapp', 'trigger'],
  },
  {
    nodeId: 'riya.queue.claim-turn',
    nodeVersion: 1,
    label: 'Claim durable turn',
    actor: 'SHARED',
    kind: 'ORCHESTRATION',
    executionRole: 'STEP',
    stage: 'IDENTIFY',
    authority: 'ORCHESTRATION_CONTROL',
    effect: 'NONE',
    status: 'IMPLEMENTED',
    implementationRef: 'apps.api.quickfurno-whatsapp.QuickFurnoWhatsAppTurnQueue.claimNext',
    description: 'Claims one durable turn with actor/conversation concurrency protection.',
    codeLocked: true,
    canvasEditable: ['retryPolicyRef'],
    groupId: 'riya.inbound',
    tags: ['queue', 'durable'],
  },
  {
    nodeId: 'riya.context.turn-material',
    nodeVersion: 1,
    label: 'Read Core turn material',
    actor: 'RIYA',
    kind: 'CONTEXT',
    executionRole: 'STEP',
    stage: 'LOAD_CONTEXT',
    authority: 'READ_ONLY',
    effect: 'READ_ONLY',
    status: 'IMPLEMENTED',
    implementationRef: 'apps.api.quickfurno-whatsapp.QuickFurnoWhatsAppMaterialReader.read',
    description: 'Reads revision-bound Core material for the exact inbound turn.',
    codeLocked: true,
    canvasEditable: ['timeoutPolicyRef', 'fallbackNodeId'],
    groupId: 'riya.context',
    tags: ['core', 'context'],
  },
  {
    nodeId: 'riya.memory.client-journey',
    nodeVersion: 1,
    label: 'Client journey memory',
    actor: 'RIYA',
    kind: 'MEMORY',
    executionRole: 'PROJECTION',
    stage: 'LOAD_CONTEXT',
    authority: 'READ_ONLY',
    effect: 'READ_ONLY',
    status: 'IMPLEMENTED',
    implementationRef: 'apps.api.quickfurno-whatsapp.contracts.clientJourney',
    description: 'Core-owned current client/requirement projection carried inside turn material.',
    codeLocked: true,
    canvasEditable: ['contextProfileRef'],
    groupId: 'riya.context',
    tags: ['memory', 'client'],
  },
  {
    nodeId: 'riya.memory.lifetime',
    nodeVersion: 1,
    label: 'Lifetime context',
    actor: 'RIYA',
    kind: 'MEMORY',
    executionRole: 'PROJECTION',
    stage: 'LOAD_CONTEXT',
    authority: 'READ_ONLY',
    effect: 'READ_ONLY',
    status: 'IMPLEMENTED',
    implementationRef: 'apps.api.quickfurno-whatsapp.riyaLifetimeContextFromMaterial',
    description:
      'Bounded returning-client, property and past-service context derived from Core material.',
    codeLocked: true,
    canvasEditable: ['contextProfileRef'],
    groupId: 'riya.context',
    tags: ['memory', 'lifetime'],
  },
  {
    nodeId: 'riya.memory.vendor-journey',
    nodeVersion: 1,
    label: 'Vendor journey',
    actor: 'RIYA',
    kind: 'MEMORY',
    executionRole: 'PROJECTION',
    stage: 'LOAD_CONTEXT',
    authority: 'READ_ONLY',
    effect: 'READ_ONLY',
    status: 'IMPLEMENTED',
    implementationRef: 'apps.api.quickfurno-whatsapp.contracts.clientVendorJourney',
    description: 'Core-owned released-vendor, contact, satisfaction and recovery projection.',
    codeLocked: true,
    canvasEditable: ['contextProfileRef'],
    groupId: 'riya.context',
    tags: ['memory', 'vendor-journey'],
  },
  {
    nodeId: 'riya.context.core-availability',
    nodeVersion: 1,
    label: 'Core availability',
    actor: 'RIYA',
    kind: 'CONTEXT',
    executionRole: 'PROJECTION',
    stage: 'LOAD_CONTEXT',
    authority: 'READ_ONLY',
    effect: 'READ_ONLY',
    status: 'IMPLEMENTED',
    implementationRef: 'apps.api.quickfurno-whatsapp.contracts.coreAvailability',
    description: 'Authoritative service/city availability supplied by QuickFurno Core.',
    codeLocked: true,
    canvasEditable: ['contextProfileRef'],
    groupId: 'riya.context',
    tags: ['core', 'availability'],
  },
  {
    nodeId: 'riya.detect.vendor-feedback',
    nodeVersion: 1,
    label: 'Detect explicit vendor feedback',
    actor: 'RIYA',
    kind: 'INTELLIGENCE',
    executionRole: 'DECISION',
    stage: 'UNDERSTAND',
    authority: 'AGENT_INTERPRET',
    effect: 'NONE',
    status: 'IMPLEMENTED',
    implementationRef: 'apps.api.quickfurno-whatsapp.feedbackForMaterial',
    description:
      'Deterministically detects narrow ordinal-bound client vendor feedback before model execution.',
    codeLocked: true,
    canvasEditable: [],
    groupId: 'riya.pre-agent-actions',
    tags: ['feedback', 'deterministic'],
  },
  {
    nodeId: 'riya.action.record-vendor-feedback',
    nodeVersion: 1,
    label: 'Record vendor feedback',
    actor: 'RIYA',
    kind: 'CAPABILITY',
    executionRole: 'CAPABILITY',
    stage: 'ACT_OR_RESPOND',
    authority: 'CORE_GOVERNED_ACTION',
    effect: 'GOVERNED_ACTION',
    status: 'IMPLEMENTED',
    implementationRef: 'apps.api.quickfurno-whatsapp.createQuickFurnoClientVendorFeedbackWriter',
    description:
      'Sends a signed evidence-bound proposal; Core independently validates before persistence.',
    codeLocked: true,
    canvasEditable: ['timeoutPolicyRef', 'retryPolicyRef', 'fallbackNodeId'],
    groupId: 'riya.pre-agent-actions',
    tags: ['core-action', 'feedback'],
  },
  {
    nodeId: 'riya.context.refresh-after-feedback',
    nodeVersion: 1,
    label: 'Refresh Core context',
    actor: 'RIYA',
    kind: 'CONTEXT',
    executionRole: 'STEP',
    stage: 'REFRESH_CONTEXT',
    authority: 'READ_ONLY',
    effect: 'READ_ONLY',
    status: 'IMPLEMENTED',
    implementationRef: 'apps.api.quickfurno-whatsapp.QuickFurnoWhatsAppMaterialReader.read',
    description: 'Re-reads Core material after accepted feedback so Riya sees accepted truth.',
    codeLocked: true,
    canvasEditable: ['timeoutPolicyRef', 'fallbackNodeId'],
    groupId: 'riya.pre-agent-actions',
    tags: ['core', 'refresh'],
  },
  {
    nodeId: 'riya.intelligence.client-os',
    nodeVersion: 1,
    label: 'Client Intelligence OS / NBA',
    actor: 'RIYA',
    kind: 'INTELLIGENCE',
    executionRole: 'DECISION',
    stage: 'DECIDE',
    authority: 'AGENT_INTERPRET',
    effect: 'PROPOSAL_ONLY',
    status: 'IMPLEMENTED',
    implementationRef: 'apps.api.quickfurno-whatsapp.buildWhatsAppClientIntelligence',
    description:
      'Builds advisory client intelligence and deterministic next-best-action from bounded Core state.',
    codeLocked: true,
    canvasEditable: ['contextProfileRef'],
    groupId: 'riya.intelligence',
    tags: ['client-os', 'nba'],
  },
  {
    nodeId: 'riya.condition.request-match',
    nodeVersion: 1,
    label: 'Should request Core match?',
    actor: 'RIYA',
    kind: 'ORCHESTRATION',
    executionRole: 'DECISION',
    stage: 'DECIDE',
    authority: 'ORCHESTRATION_CONTROL',
    effect: 'NONE',
    status: 'IMPLEMENTED',
    implementationRef: 'apps.api.quickfurno-whatsapp.shouldRequestCoreMatch',
    description:
      'Allows a match request only when the typed Client OS next-best-action is REQUEST_MATCH.',
    codeLocked: true,
    canvasEditable: ['conditionRef'],
    groupId: 'riya.pre-agent-actions',
    tags: ['condition', 'match'],
  },
  {
    nodeId: 'riya.action.request-match',
    nodeVersion: 1,
    label: 'Request Core match',
    actor: 'RIYA',
    kind: 'CAPABILITY',
    executionRole: 'CAPABILITY',
    stage: 'ACT_OR_RESPOND',
    authority: 'CORE_GOVERNED_ACTION',
    effect: 'GOVERNED_ACTION',
    status: 'IMPLEMENTED',
    implementationRef: 'apps.api.quickfurno-whatsapp.createQuickFurnoClientMatchRequestWriter',
    description:
      'Sends signed revision-bound match request; Core revalidates readiness and owns matching.',
    codeLocked: true,
    canvasEditable: ['timeoutPolicyRef', 'retryPolicyRef', 'fallbackNodeId'],
    groupId: 'riya.pre-agent-actions',
    tags: ['core-action', 'matching'],
  },
  {
    nodeId: 'riya.context.refresh-after-match',
    nodeVersion: 1,
    label: 'Refresh match state',
    actor: 'RIYA',
    kind: 'CONTEXT',
    executionRole: 'STEP',
    stage: 'REFRESH_CONTEXT',
    authority: 'READ_ONLY',
    effect: 'READ_ONLY',
    status: 'IMPLEMENTED',
    implementationRef: 'apps.api.quickfurno-whatsapp.QuickFurnoWhatsAppMaterialReader.read',
    description: 'Re-reads Core material after a match action before model response generation.',
    codeLocked: true,
    canvasEditable: ['timeoutPolicyRef', 'fallbackNodeId'],
    groupId: 'riya.pre-agent-actions',
    tags: ['core', 'refresh', 'matching'],
  },
  {
    nodeId: 'riya.context.conversation',
    nodeVersion: 1,
    label: 'Conversation context',
    actor: 'RIYA',
    kind: 'CONTEXT',
    executionRole: 'STEP',
    stage: 'LOAD_CONTEXT',
    authority: 'READ_ONLY',
    effect: 'READ_ONLY',
    status: 'IMPLEMENTED',
    implementationRef:
      'apps.api.quickfurno-whatsapp.QuickFurnoWhatsAppConversationContextReader.read',
    description: 'Loads bounded conversation context in parallel with Core turn material.',
    codeLocked: true,
    canvasEditable: ['contextProfileRef', 'timeoutPolicyRef'],
    groupId: 'riya.context',
    tags: ['conversation', 'context'],
  },
  {
    nodeId: 'riya.agent.specialist-runtime',
    nodeVersion: 1,
    label: 'Riya specialist runtime',
    actor: 'RIYA',
    kind: 'INTELLIGENCE',
    executionRole: 'STEP',
    stage: 'UNDERSTAND',
    authority: 'AGENT_PROPOSE',
    effect: 'PROPOSAL_ONLY',
    status: 'IMPLEMENTED',
    implementationRef: 'apps.api.quickfurno-whatsapp.createQuickFurnoWhatsAppSpecialistRuntime',
    description:
      'Composes Riya continuity, semantic context, prompt/model route, governed knowledge and proposal generation.',
    codeLocked: true,
    canvasEditable: [
      'contextProfileRef',
      'promptProfileRef',
      'modelRoutingProfileRef',
      'toolProfileRef',
      'fallbackNodeId',
    ],
    groupId: 'riya.intelligence',
    tags: ['riya', 'model', 'prompt', 'rag'],
  },
  {
    nodeId: 'riya.action.write-reply',
    nodeVersion: 1,
    label: 'Queue governed reply',
    actor: 'SHARED',
    kind: 'CHANNEL',
    executionRole: 'CHANNEL',
    stage: 'ACT_OR_RESPOND',
    authority: 'CORE_GOVERNED_ACTION',
    effect: 'CHANNEL_REQUEST',
    status: 'IMPLEMENTED',
    implementationRef: 'apps.api.quickfurno-whatsapp.createQuickFurnoWhatsAppReplyWriter',
    description:
      'Submits the Riya reply through the signed Core reply boundary; Jarvis does not send directly.',
    codeLocked: true,
    canvasEditable: ['timeoutPolicyRef', 'retryPolicyRef', 'fallbackNodeId'],
    groupId: 'riya.response',
    tags: ['reply', 'whatsapp', 'core'],
  },
  {
    nodeId: 'riya.queue.complete',
    nodeVersion: 1,
    label: 'Finalize durable turn',
    actor: 'SHARED',
    kind: 'SYSTEM',
    executionRole: 'TERMINAL',
    stage: 'WAIT_CONTINUE_CLOSE',
    authority: 'ORCHESTRATION_CONTROL',
    effect: 'NONE',
    status: 'IMPLEMENTED',
    implementationRef: 'apps.api.quickfurno-whatsapp.QuickFurnoWhatsAppTurnQueue.complete',
    description: 'Marks the claimed turn complete after the governed reply/result is accepted.',
    codeLocked: true,
    canvasEditable: [],
    groupId: 'riya.response',
    tags: ['queue', 'terminal'],
  },
] as const;

const edges: readonly AgentFlowEdgeDefinition[] = [
  {
    edgeId: 'e.01',
    sourceNodeId: 'riya.trigger.whatsapp-inbound',
    targetNodeId: 'riya.queue.claim-turn',
    kind: 'CONTROL',
  },
  {
    edgeId: 'e.02',
    sourceNodeId: 'riya.queue.claim-turn',
    targetNodeId: 'riya.context.turn-material',
    kind: 'CONTROL',
  },
  {
    edgeId: 'e.03',
    sourceNodeId: 'riya.queue.claim-turn',
    targetNodeId: 'riya.context.conversation',
    kind: 'CONTROL',
    label: 'parallel context read',
  },
  {
    edgeId: 'e.04',
    sourceNodeId: 'riya.context.turn-material',
    targetNodeId: 'riya.memory.client-journey',
    kind: 'DATA',
    label: 'contains',
  },
  {
    edgeId: 'e.05',
    sourceNodeId: 'riya.context.turn-material',
    targetNodeId: 'riya.memory.lifetime',
    kind: 'DATA',
    label: 'contains / derives',
  },
  {
    edgeId: 'e.06',
    sourceNodeId: 'riya.context.turn-material',
    targetNodeId: 'riya.memory.vendor-journey',
    kind: 'DATA',
    label: 'contains',
  },
  {
    edgeId: 'e.07',
    sourceNodeId: 'riya.context.turn-material',
    targetNodeId: 'riya.context.core-availability',
    kind: 'DATA',
    label: 'contains',
  },
  {
    edgeId: 'e.08',
    sourceNodeId: 'riya.context.turn-material',
    targetNodeId: 'riya.detect.vendor-feedback',
    kind: 'CONTROL',
  },
  {
    edgeId: 'e.09',
    sourceNodeId: 'riya.detect.vendor-feedback',
    targetNodeId: 'riya.action.record-vendor-feedback',
    kind: 'COMMAND',
    label: 'explicit feedback',
    conditionRef: 'riya.feedback.detected',
  },
  {
    edgeId: 'e.10',
    sourceNodeId: 'riya.action.record-vendor-feedback',
    targetNodeId: 'riya.context.refresh-after-feedback',
    kind: 'RESULT',
    label: 'accepted/already recorded',
  },
  {
    edgeId: 'e.11',
    sourceNodeId: 'riya.context.refresh-after-feedback',
    targetNodeId: 'riya.intelligence.client-os',
    kind: 'DATA',
  },
  {
    edgeId: 'e.12',
    sourceNodeId: 'riya.detect.vendor-feedback',
    targetNodeId: 'riya.intelligence.client-os',
    kind: 'CONTROL',
    label: 'no explicit feedback',
    conditionRef: 'riya.feedback.none',
  },
  {
    edgeId: 'e.13',
    sourceNodeId: 'riya.intelligence.client-os',
    targetNodeId: 'riya.condition.request-match',
    kind: 'DATA',
  },
  {
    edgeId: 'e.14',
    sourceNodeId: 'riya.condition.request-match',
    targetNodeId: 'riya.action.request-match',
    kind: 'COMMAND',
    label: 'REQUEST_MATCH',
    conditionRef: 'riya.nba.request-match',
  },
  {
    edgeId: 'e.15',
    sourceNodeId: 'riya.action.request-match',
    targetNodeId: 'riya.context.refresh-after-match',
    kind: 'RESULT',
  },
  {
    edgeId: 'e.16',
    sourceNodeId: 'riya.context.refresh-after-match',
    targetNodeId: 'riya.agent.specialist-runtime',
    kind: 'DATA',
  },
  {
    edgeId: 'e.17',
    sourceNodeId: 'riya.condition.request-match',
    targetNodeId: 'riya.agent.specialist-runtime',
    kind: 'CONTROL',
    label: 'no pre-agent match',
    conditionRef: 'riya.nba.no-match-action',
  },
  {
    edgeId: 'e.18',
    sourceNodeId: 'riya.context.conversation',
    targetNodeId: 'riya.agent.specialist-runtime',
    kind: 'DATA',
  },
  {
    edgeId: 'e.19',
    sourceNodeId: 'riya.memory.client-journey',
    targetNodeId: 'riya.agent.specialist-runtime',
    kind: 'DATA',
  },
  {
    edgeId: 'e.20',
    sourceNodeId: 'riya.memory.lifetime',
    targetNodeId: 'riya.agent.specialist-runtime',
    kind: 'DATA',
  },
  {
    edgeId: 'e.21',
    sourceNodeId: 'riya.memory.vendor-journey',
    targetNodeId: 'riya.agent.specialist-runtime',
    kind: 'DATA',
  },
  {
    edgeId: 'e.22',
    sourceNodeId: 'riya.context.core-availability',
    targetNodeId: 'riya.agent.specialist-runtime',
    kind: 'DATA',
  },
  {
    edgeId: 'e.23',
    sourceNodeId: 'riya.agent.specialist-runtime',
    targetNodeId: 'riya.action.write-reply',
    kind: 'COMMAND',
    label: 'proposal',
  },
  {
    edgeId: 'e.24',
    sourceNodeId: 'riya.action.write-reply',
    targetNodeId: 'riya.queue.complete',
    kind: 'RESULT',
  },
] as const;

export const RIYA_WHATSAPP_CLIENT_FLOW_V1 = createAgentFlowDefinition({
  flowId: 'agent-flow.riya.whatsapp-client.v1',
  flowVersion: 1,
  label: 'Riya — WhatsApp client journey',
  actor: 'RIYA',
  status: 'IMPLEMENTED',
  description: 'Read-only architecture map of the current governed Riya WhatsApp turn path.',
  rootNodeId: 'riya.trigger.whatsapp-inbound',
  groups,
  nodes,
  edges,
});
